### PR TITLE
Driver Bid Backend

### PR DESCRIPTION
**Pull request by jaczhi**
Related to, but does not close, #21 

* Create REST object in backend for bids
* Allow drivers to create, modify, and delete bids
* Check for conditions when these actions are not allowed
* Write unit tests for driver controller

### CODE REVIEW

**Review by RuralBrick — APPROVED** [review]
@jaczhi Looks good. Theoretically, I wouldn't want drivers to be able to raise a bid's amount or delete a bid themselves, but I guess we can keep these routes as utility for frontend and/or ourselves.

**Comment by jaczhi** [comment]
@RuralBrick  i could be mistaken, but i thought the consensus was that drivers could modify bids (to maintain competitiveness) or retract bids (if they went for another trip) as long as the trip isn't confirmed?

**Comment by RuralBrick** [comment]
@jaczhi I remember discussing Riders are able to retract trips and Drivers can only lower their bids, but if you think the other way leads to a better user experience, then I have no objections.

**Review by warrickhe — APPROVED** [review]
Looks good to me

**Pull request merged**
